on:
  pull_request:
  push:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
    name: "nix-build"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
    - uses: cachix/install-nix-action@v11
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20200820_4d77513/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v6
      with:
        name: utdemir
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix build
    - run: nix develop --command 'echo' 'ok.'
