name: "nix-build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v5
      with:
        name: utdemir
        file: default.nix
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
